// <auto-generated />
namespace iTed2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddType7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddType7));
        
        string IMigrationMetadata.Id
        {
            get { return "201411241715588_AddType7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
